/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#ffb59f",
        "amber-bg": "#FFDDB8",
        "on-surface": "#191b23",
        "inverse-on-surface": "#f0f0fb",
        "on-error-container": "#93000a",
        "text-secondary": "#565E74",
        "primary-fixed-dim": "#b5c4ff",
        "secondary-fixed": "#dbe1ff",
        "on-primary": "#ffffff",
        "error-promo": "#BA1A1A",
        "on-background": "#191b23",
        "card-bg": "#FFFFFF",
        "on-primary-fixed": "#00164d",
        "outline": "#737686",
        "on-primary-fixed-variant": "#003cac",
        "on-error": "#ffffff",
        "secondary-container": "#085efe",
        "secondary": "#0049cb",
        "primary": "#003599",
        "background": "#faf8ff",
        "tertiary-container": "#9e2c02",
        "surface-dim": "#d9d9e4",
        "on-tertiary-container": "#ffbaa6",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b5c4ff",
        "inverse-surface": "#2e3038",
        "on-tertiary-fixed": "#3a0a00",
        "on-secondary-fixed": "#00164d",
        "primary-container": "#0049cc",
        "on-secondary-container": "#eeefff",
        "page-background": "#F8F9FF",
        "error-container": "#ffdad6",
        "surface-variant": "#e2e1ed",
        "on-tertiary-fixed-variant": "#862300",
        "surface-bright": "#faf8ff",
        "amber-text": "#9A6100",
        "secondary-fixed-dim": "#b5c4ff",
        "text-primary": "#0B1C30",
        "surface-container-highest": "#e2e1ed",
        "tertiary": "#761e00",
        "on-tertiary": "#ffffff",
        "placeholder": "#EEF2F9",
        "surface-tint": "#1a53d5",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#003cac",
        "outline-variant": "#c3c5d7",
        "surface-container-high": "#e7e7f2",
        "on-surface-variant": "#434654",
        "on-primary-container": "#bac9ff",
        "surface": "#EFF4FF",
        "surface-container": "#ededf8",
        "error": "#ba1a1a",
        "surface-container-low": "#f3f3fe",
        "tertiary-fixed": "#ffdbd1",
        "border-subtle": "#E3E9F5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-lg": "1rem",
        "space-2xl": "2rem",
        "margin": "2rem",
        "space-md": "0.75rem",
        "space-xl": "1.5rem",
        "space-sm": "0.5rem",
        "space-3xl": "4rem",
        "space-xs": "0.25rem",
        "gutter": "1rem"
      },
      fontFamily: {
        "headline-hero": ["Plus Jakarta Sans"],
        "title-card": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-section-mobile": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-section": ["Plus Jakarta Sans"],
        "sku": ["monospace"],
        "headline-hero-mobile": ["Plus Jakarta Sans"],
        "price": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-hero": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "title-card": ["16px", { "lineHeight": "22px", "fontWeight": "600" }],
        "body-md": ["15px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-section-mobile": ["22px", { "lineHeight": "28px", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-section": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "sku": ["11px", { "lineHeight": "14px", "fontWeight": "400" }],
        "headline-hero-mobile": ["28px", { "lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "price": ["18px", { "lineHeight": "24px", "fontWeight": "700" }]
      },
      keyframes: {
        slideUp: {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fade: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        }
      },
      animation: {
        slideUp: 'slideUp 0.25s ease-out',
        fade: 'fade 0.3s ease-out',
      },
    }
  },
  plugins: [],
}
